// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://npmyobeqbipvvuaeswnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wbXlvYmVxYmlwdnZ1YWVzd251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDk0MjksImV4cCI6MjA3MjQ4NTQyOX0.Gba__aB1PkpHkOQbNHxPZ3OtmML_vAMsUebL38FTMJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Export resumable upload endpoint for large files (TUS protocol)
const projectRef = SUPABASE_URL.split('//')[1].split('.')[0];
export const SUPABASE_STORAGE_RESUMABLE_URL = `https://${projectRef}.supabase.co/storage/v1/upload/resumable`;